name: Pipeline

on:
    push:
        branches: [main]

env:
    ARTIFACT_PATH: "build/index.html"
    ARTIFACT_NAME: "build-dir"

jobs:
    linting:
        runs-on: ubuntu-latest
        name: "Run python linters"
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
            - name: "Install python modules"
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: "Run flake8"
              run: flake8 main.py
            - name: "Run pylint"
              run: pylint main.py
    unit-test:
        runs-on: ubuntu-latest
        name: "Run unit tests"
        needs: [linting]
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
            - name: "Run unit tests"
              run: python -m unittest --verbose --failfast
    create-artifact:
        runs-on: ubuntu-latest
        name: "Create artifact"
        needs: [unit-test]
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
            - name: "Run program"
              run: python main.py
            - name: "Upload artifact"
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ env.ARTIFACT_NAME }}
                  path: ${{ env.ARTIFACT_PATH }}
    deploy:
        runs-on: ubuntu-latest
        name: "Deploy to production"
        needs: [create-artifact]
        env:
            DEPLOY_URL: "https://cs.uns.edu.ar/~jose.moyano/index.php"
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
            - name: "Download artifact"
              uses: actions/download-artifact@v3
              with:
                  name: ${{ env.ARTIFACT_NAME }}
            - name: "Move file"
              run: |
                mkdir -p build
                mv index.html ./build/index.html
            - name: "Deploy to remote"
              run: |
                  result=$(curl -v --stderr deploy.log -w "%{http_code}\n" -F password="${{ secrets.SERVER_PASSWORD }}" -F file=@build/index.html -F user="${{ secrets.SERVER_USERNAME }}" "${{ env.DEPLOY_URL }}")
                  echo $result | tail -n 1 | grep "200" > /dev/null || (echo "Error en la solicitud"; exit 1)
            - name: "Upload logs"
              uses: actions/upload-artifact@v3
              with:
                  name: logs
                  path: "deploy.log"
